{
  lib,
  pkgs,
  ...
}: {
  # Type this command after ssh login so that
  # you would be asked for the decryption password in initrd stage
  # `systemd-tty-ask-password-agent`

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "virtio_net"
        "virtio-pci"
      ];
      kernelModules = [
        "virtio_net"
        "virtio-pci"
      ];
      network = {
        # see https://mynixos.com/nixpkgs/option/boot.initrd.network.enable
        enable = true;
        ssh = {
          enable = true;
          port = 222; # Recommend set this as the same as config.services.openssh.ports
          authorizedKeys = [
            # Could be generated by command `ssh-keygen -t ed25519 -a 256 -C "root@${hostname}"`
            # This could be the same as users.users.root.openssh.authorizedKeys.keys
            ''
              ssh-ed25519 xxxxxx
            ''
          ];
          hostKeys = ["/etc/secrets/initrd/ssh_hostKey"];
        };
      };
      secrets = lib.mkForce {
        "/etc/secrets/initrd/ssh_hostKey" = pkgs.writeText "hostKey" ''
          -----BEGIN OPENSSH PRIVATE KEY-----
          xxxxxx
          -----END OPENSSH PRIVATE KEY-----
        '';
      };
    };
    kernelParams = ["ip=192.168.1.100::192.168.1.1:255.255.255.0::eth0:none"];
  };
  environment.etc = {
    # Could be generated by command
    # ssh-keygen -t ed25519 -N "" -C ssh@${hostname}
    # Notice: The hostKey should not have passphrase,
    "ssh/ssh_hostKey" = {
      mode = "0600";
      text = ''
        -----BEGIN OPENSSH PRIVATE KEY-----
        xxxxxx
        -----END OPENSSH PRIVATE KEY-----
      '';
    };
    # Notice: this should be not the same as boot.initrd.network.ssh.authorizedKeys or users.users.root.openssh.authorizedKeys.keys
    "ssh/ssh_hostKey.pub" = {
      mode = "0600";
      text = ''
        ssh-ed25519 xxxxxx
      '';
    };
  };

  services.openssh.hostKeys = [
    {
      path = "/etc/ssh/ssh_hostKey";
      type = "ed25519";
    }
  ];
}
