_: {
  users.users.root = {
    hashedPassword = "xxxxxx"; # Could be generated by command `mkpasswd`
    openssh.authorizedKeys.keys = [
      ''
        ssh-ed25519 xxxxxx
      ''
      # Could be generated by command `ssh-keygen`
    ];
  };
}
