{ lib, ... }:
{
  imports = [
    ./hardware.nix
    ]
      ++ lib.filesystem.listFilesRecursive ../../modules
      ++ lib.filesystem.listFilesRecursive ../../packages/essential;

  # bootloader
  boot.loader.grub = {
    configurationLimit = 10;
    enable = true;
    device = "/dev/sda";
  };

  # swap
  swapDevices = [{ device = "/swapfile"; size = 2048; }];

  # systemd network config
  systemd.network = {
    enable = true;
    networks.eth0 = {
      address = [
        "xxxxxx"
      ];
      gateway = [ "xxxxxx" ];
      matchConfig.Name = "eth0";
      networkConfig = {
        IPv6AcceptRA = false;
      };
      routes = [
        {
          Gateway = "xxxxxx";
          GatewayOnLink = true;
        }
      ];
    };
  };

  # users
  users = {
    mutableUsers = false;
    users.root = {
      hashedPassword = "xxxxxx"; # could be generated by mkpasswd -m SHA-512
      openssh.authorizedKeys.keys = [
        "xxxxxx"
      ];
    };
  };
}
