_: {
  virtualisation.oci-containers.containers."oidcwarden" = {
    image = "ghcr.io/timshel/oidcwarden:latest";
    pull = "newer";

    environment = {
      # see https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
      # OIDC redirect(CallBack) URL format: https://example.com/identity/connect/oidc-signin
      "ADMIN_TOKEN" = ""; # could be generated by command `podman run --rm -it vaultwarden/server:latest /vaultwarden hash`
      "DOMAIN" = "https://vault.example.com";
      "INVITATIONS_ALLOWED" = "false";
      "LOG_LEVEL" = "warn";
      "ROCKET_ADDRESS" = "0.0.0.0";
      "ROCKET_PORT" = "8000";
      "ROCKET_PROFILE" = "release";

      "SHOW_PASSWORD_HINT" = "false";
      "SIGNUPS_ALLOWED" = "false";
      "SIGNUPS_VERIFY" = "false";

      "SMTP_HOST" = "mail.example.com";
      "SMTP_PORT" = "587";
      "SMTP_SECURITY" = "starttls";
      "SMTP_FROM" = "do-not-reply@example.com";
      "SMTP_FROM_NAME" = "do-not-reply@example.com";
      "SMTP_USERNAME" = "do-not-reply@example.com";
      "SMTP_PASSWORD" = "xxxxxx";

      "SSO_ENABLED" = "true";
      "SSO_ONLY" = "true";
      "SSO_AUTH_ONLY_NOT_SESSION" = "true";
      "SSO_AUTHORITY" = "https://auth.example.com/oidc";
      "SSO_CLIENT_ID" = "n7D88PN8SDtktc4i";
      "SSO_CLIENT_SECRET" = "RwVdeRlzoqt8xV1dASpd3EJafMfsiW5O";
      "SSO_SCOPES" = "openid profile email";
      "SSO_PKCE" = "true";
      "SSO_SIGNUPS_MATCH_EMAIL" = "true";
      "SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION" = "true";
    };

    volumes = [
      "oidcwarden:/data:rw"
    ];

    ports = [
      "127.0.0.1:11180:8000/tcp"
    ];
  };
}
