{ pkgs, ... }:
let
  postgresUrl = "postgres://kan:xxxxxx@postgres/kan?sslmode=disable";
in
{
  virtualisation.oci-containers.containers."kan-web" = {
    image = "ghcr.io/kanbn/kan:latest";
    pull = "newer";
    environment = {
      "NEXT_PUBLIC_BASE_URL" = "https://kan.example.com";
      "POSTGRES_URL" = postgresUrl;

      # OIDC SSO
      # Callback URL: {BETTER_AUTH_URL}/api/auth/oauth2/callback/oidc
      "BETTER_AUTH_SECRET" = ""; # Could be generated by command `npx @better-auth/cli secret`
      "OIDC_DISCOVERY_URL" = "https://auth.example.com/oidc/.well-known/openid-configuration";
      "OIDC_CLIENT_ID" = "xxxxxx";
      "OIDC_CLIENT_SECRET" = "xxxxxx";
      "NEXT_PUBLIC_ALLOW_CREDENTIALS" = "false";
      "NEXT_PUBLIC_DISABLE_EMAIL" = "true";
      "NEXT_PUBLIC_DISABLE_SIGN_UP" = "false";

      # S3
      "S3_ENDPOINT" = "https://s3.example.com";
      "S3_REGION" = "rustfs";
      "S3_FORCE_PATH_STYLE" = "true";
      "S3_ACCESS_KEY_ID" = "xxxxxx";
      "S3_SECRET_ACCESS_KEY" = "xxxxxx";
      "S3_AVATAR_UPLOAD_LIMIT" = "20971520"; # 20MB
      "NEXT_PUBLIC_AVATAR_BUCKET_NAME" = "kan-avatars";
      "NEXT_PUBLIC_ATTACHMENTS_BUCKET_NAME" = "kan-attachments";
      "NEXT_PUBLIC_STORAGE_URL" = "https://s3.example.com";
      "NEXT_PUBLIC_STORAGE_DOMAIN" = "s3.example.com";
      "NEXT_PUBLIC_USE_VIRTUAL_HOSTED_URLS" = "false";

      "NEXT_PUBLIC_WHITE_LABEL_HIDE_POWERED_BY" = "true";
      "LOG_LEVEL" = "info";
    };
    ports = [
      "127.0.0.1:51349:3000/tcp"
    ];
  };

  systemd.services.podman-kan-web = {
    after = [ "podman-kan-migrate.service" ];
    requires = [ "podman-kan-migrate.service" ];
  };

  systemd.services.podman-kan-migrate = {
    description = "kan-migrate";
    wantedBy = [ "multi-user.target" ];
    path = with pkgs; [ zfs ];
    after = [
      "podman-postgres.service"
      "create-pg-db-for-kan.service"
    ];
    requires = [
      "podman-postgres.service"
      "create-pg-db-for-kan.service"
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      ${pkgs.podman}/bin/podman run --rm \
        -e POSTGRES_URL=${postgresUrl} \
        ghcr.io/kanbn/kan-migrate:latest
    '';
  };

  systemd.services.create-pg-db-for-kan = {
    wantedBy = [ "multi-user.target" ];
    after = [ "podman-postgres.service" ];
    description = "Initialize PostgreSQL users and databases for kan";
    path = with pkgs; [ zfs ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart =
        let
          psql = "${pkgs.podman}/bin/podman exec -i postgres psql -U postgres";
        in
        pkgs.writeShellScript "create-pg-db-for-kan" ''
          if ${psql} -tAc "SELECT 1 FROM pg_database WHERE datname='kan'" | grep -q 1; then
            echo "Database 'kan' already exists, skipping initialization."
            exit 0
          fi

          echo "Creating role and database for kan..."
          ${psql} \
            -c "CREATE ROLE kan WITH LOGIN PASSWORD 'xxxxxx';" \
            -c "CREATE DATABASE kan WITH ENCODING='UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE=template0 OWNER=kan;"
        '';
    };
  };
}
