_: {
  virtualisation.oci-containers.containers."bettershift" = {
    image = "ghcr.io/pantelx/bettershift:latest";
    pull = "newer";
    environment = {
      # Auth
      "AUTH_ENABLED" = "true";
      "BETTER_AUTH_URL" = "https://shift.example.com";
      "BETTER_AUTH_SECRET" = ""; # Could be generated by command `npx @better-auth/cli secret`

      # OIDC SSO
      # Callback URL: {BETTER_AUTH_URL}/api/auth/oauth2/callback/custom-oidc
      "CUSTOM_OIDC_ENABLED" = "true";
      "CUSTOM_OIDC_NAME" = "";
      "CUSTOM_OIDC_CLIENT_ID" = "";
      "CUSTOM_OIDC_CLIENT_SECRET" = "";
      "CUSTOM_OIDC_ISSUER" = "https://auth.example.com/oidc/.well-known/openid-configuration";
      "CUSTOM_OIDC_SCOPES" = "openid profile email";

      "DATABASE_URL" = "file:./data/sqlite.db";
      "NODE_ENV" = "production";
      "HOSTNAME" = "0.0.0.0";
      "DEFAULT_LOCALE" = "en";
      "TZ" = "Asia/Singapore";

      "ALLOW_USER_REGISTRATION" = "true";
      "ALLOW_GUEST_ACCESS" = "false";
    };
    volumes = [
      "bettershift:/app/data"
    ];
    ports = [
      "127.0.0.1:58490:3000/tcp"
    ];
  };
}
