_: {
  virtualisation.oci-containers.containers."scrumboy" = {
    pull = "newer";
    image = "ghcr.io/markrai/scrumboy:latest";
    environment = {
      BIND_ADDR = ":8080";

      SCRUMBOY_ENCRYPTION_KEY = ""; # could be generated by command `openssl rand -base64 32`
      SCRUMBOY_OIDC_ISSUER = "https://auth.example.com/oidc";
      SCRUMBOY_OIDC_CLIENT_ID = "xxxxxx";
      SCRUMBOY_OIDC_CLIENT_SECRET = "xxxxxx";
      SCRUMBOY_OIDC_REDIRECT_URL = "https://board.example.com/api/auth/oidc/callback";
      SCRUMBOY_OIDC_LOCAL_AUTH_DISABLED = "true";
    };
    volumes = [
      "scrumboy:/data:rw"
    ];
    ports = [
      "127.0.0.1:57316:8080"
    ];
  };
}
